name: Cleanup Old Workflow Runs

on:
  workflow_dispatch:
    inputs:
      workflow_name:
        description: "Workflow name to clean (e.g., Compile, Test, Solidity CI, Verify on BscScan)"
        required: true
        type: string
      keep:
        description: "How many latest runs to keep"
        required: true
        default: "3"
        type: choice
        options: ["1", "2", "3", "5", "10"]

permissions:
  actions: write
  contents: read

concurrency:
  group: cleanup-${{ github.event.inputs.workflow_name }}
  cancel-in-progress: true

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old runs (keep N)
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          workflow: ${{ github.event.inputs.workflow_name }}
          retain_days: 0
          keep_minimum_runs: ${{ github.event.inputs.keep }}
