name: Compile

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Show tool versions
        run: |
          node -v
          npm -v
          npm config get engine-strict --location=project || true

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci || npm ci --legacy-peer-deps
          else
            npm install --legacy-peer-deps
          fi

      # (Opsional) Hindari ikut meng-compile file flatten untuk verifikasi
      - name: Remove flattened contracts (if any)
        run: |
          find contracts -name "*_flat.sol" -delete || true

      - name: Compile contracts
        run: |
          npx hardhat clean
          npx hardhat compile --force

      # Simpan artefak utama (selalu upload, bahkan jika step sebelumnya gagal)
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: hardhat-artifacts-${{ github.sha }}
          path: |
            artifacts/
            cache/
            typechain-types/
          if-no-files-found: warn
          retention-days: 1
          compression-level: 6

      # (Opsional) Simpan build-info & debug logs terpisah
      - name: Upload build-info
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: hardhat-build-info-${{ github.sha }}
          path: artifacts/build-info/
          if-no-files-found: ignore
          retention-days: 1
          compression-level: 6
