name: Compile

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  compile:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci || npm ci --legacy-peer-deps
          else
            npm install --legacy-peer-deps
          fi

      - name: Compile contracts
        run: |
          npx hardhat clean
          npx hardhat compile

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hardhat-artifacts-${{ github.sha }}
          path: |
            artifacts/
            cache/
            typechain-types/
          if-no-files-found: warn
          retention-days: 7
          compression-level: 6
