name: Roadmap Auto Check

on:
  push:
    branches: [main]
    paths:
      - "README.md"
      - "docs/Whitepaper.md"
      - "docs/roadmap*"
      - ".github/workflows/roadmap-auto-check.yml"
      
  # Auto-jalan ketika workflow tertentu selesai
  workflow_run:
    workflows:
      - "Verify on BscScan"
      - "Whitepaper release"
    types: [completed]

  # Bisa dijalankan manual dari tab Actions
  workflow_dispatch:
    inputs:
      key:
        description: "ROADMAP key to check"
        required: true
        default: "VERIFY"
        type: choice
        options:
          - VERIFY
          - WHITEPAPER
          - WEBSITE
          - LIQ
          - AIRDROP
          - LISTINGS
          - QUESTS
          - STAKING
          - AI
          - PARTNERS
          - BURN
          - CEX
          - COMMUNITY

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  update-roadmap:
    # ⬇️ tambahkan push di sini
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Decide ROADMAP key
        id: key
        shell: bash
        run: |
          KEY=""
          if [ "${{ github.event_name }}" = "workflow_run" ]; then
            case "${{ github.event.workflow_run.name }}" in
              "Verify on BscScan") KEY="VERIFY" ;;
              "Whitepaper release") KEY="WHITEPAPER" ;;
              # tambahkan mapping lain bila perlu
            esac
          else
            KEY="${{ inputs.key }}"
          fi
          echo "key=$KEY" >> "$GITHUB_OUTPUT"

      - name: Update README and Whitepaper (green badge, replace old)
        if: steps.key.outputs.key != ''
        shell: bash
        run: |
          set -e
          KEY="${{ steps.key.outputs.key }}"
          DATE="$(date +'%Y-%m-%d')"
          DATE_SHIELDS="${DATE//-/"--"}"
          BADGE="![done ${DATE}](https://img.shields.io/badge/done-${DATE_SHIELDS}-brightgreen?style=flat-square)"

          mark_done () {
            FILE="$1"
            MARK="<!-- ROADMAP:${KEY} -->"
            [ -f "$FILE" ] || return 0

            awk -v mark="$MARK" -v badge="$BADGE" '
            {
              if ($0 ~ mark) {
                if ($0 ~ /^\s*-\s*\[\s\]\s/) { sub(/\[\s\]/, "[x]") }
                gsub(/\(done[[:space:]]+[0-9]{4}-[0-9]{2}-[0-9]{2}\)/, "")
                gsub(/ *!\[done[[:space:]]+[0-9-]+\]\(https:\/\/img\.shields\.io\/badge\/done-[0-9-]+-brightgreen\?style=flat-square\)/, "")
                sub(/[[:space:]]+$/, "")
                $0 = $0 " " badge
              }
              print
            }' "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"
          }

          mark_done "README.md"
          mark_done "docs/Whitepaper.md"

          if git status --porcelain | grep -E "README\.md|docs/Whitepaper\.md" >/dev/null; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md docs/Whitepaper.md
            git commit -m "chore(roadmap): mark ${KEY} done on ${DATE} (green badge)"
            git push
          else
            echo "No roadmap changes to commit."
          fi

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: roadmap-logs-${{ github.sha }}
          path: ./.logs/
          if-no-files-found: ignore
          retention-days: 1
          compression-level: 6
          
