name: Roadmap Auto Check

on:
  # Otomatis saat workflow tertentu sukses
  workflow_run:
    workflows:
      - "Verify on BscScan"
      - "Whitepaper release"
    types: [completed]

  # Bisa juga manual dari tab Actions
  workflow_dispatch:
    inputs:
      key:
        description: "ROADMAP key to check"
        required: true
        default: "VERIFY"
        type: choice
        options:
          - VERIFY
          - WHITEPAPER
          - WEBSITE
          - LIQ
          - AIRDROP
          - LISTINGS
          - QUESTS
          - STAKING
          - AI
          - PARTNERS
          - BURN
          - CEX
          - COMMUNITY

permissions:
  contents: write

jobs:
  update-roadmap:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Decide ROADMAP key
        id: key
        shell: bash
        run: |
          KEY=""
          if [ "${{ github.event_name }}" = "workflow_run" ]; then
            case "${{ github.event.workflow_run.name }}" in
              "Verify on BscScan") KEY="VERIFY" ;;
              "Whitepaper release") KEY="WHITEPAPER" ;;
              # Tambahkan mapping lain jika perlu
            esac
          else
            KEY="${{ inputs.key }}"
          fi
          echo "key=$KEY" >> "$GITHUB_OUTPUT"

      - name: Update README and Whitepaper
        if: steps.key.outputs.key != ''
        shell: bash
        run: |
          set -e
          KEY="${{ steps.key.outputs.key }}"
          DATE="$(date +'%Y-%m-%d')"

          mark_done () {
            FILE="$1"
            MARK="<!-- ROADMAP:${KEY} -->"
            [ -f "$FILE" ] || return 0

            awk -v key="$MARK" -v date="$DATE" '
            {
              if ($0 ~ key) {
                # Jika masih kosong [ ]
                if ($0 ~ /^\s*-\s*\[\s\]\s/) {
                  sub(/\[\s\]/, "✅")
                  if ($0 !~ /done /) { $0 = $0 " (done " date ")" }
                }
                # Jika sudah [x], ubah juga jadi ✅
                else if ($0 ~ /^\s*-\s*\[x\]\s/) {
                  sub(/\[x\]/, "✅")
                  if ($0 !~ /done /) { $0 = $0 " (done " date ")" }
                }
              }
              print
            }' "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"
          }

          mark_done "README.md"
          mark_done "docs/Whitepaper.md"

          if git status --porcelain | grep -E "README\.md|docs/Whitepaper\.md" >/dev/null; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md docs/Whitepaper.md
            git commit -m "chore(roadmap): auto-check $KEY on $DATE"
            git push
          else
            echo "No roadmap changes to commit."
          fi
