name: Roadmap Auto Check

on:
  # Otomatis ketika workflow "Verify on BscScan" selesai (dan sukses)
  workflow_run:
    workflows: ["Verify on BscScan"]
    types: [completed]

  # Bisa juga dijalankan manual dari tab Actions
  workflow_dispatch:
    inputs:
      task:
        description: "ROADMAP key to check"
        required: true
        default: "VERIFY"
        type: choice
        options:
          - VERIFY
          - WHITEPAPER
          - WEBSITE
          - LIQ
          - AIRDROP
          - LISTINGS
          - QUESTS
          - STAKING
          - AI
          - PARTNERS
          - BURN
          - CEX
          - COMMUNITY

permissions:
  contents: write

jobs:
  update-roadmap:
    # Jalan jika manual, atau jika workflow_run sukses
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Decide ROADMAP key
        id: key
        shell: bash
        run: |
          KEY=""
          if [ "${{ github.event_name }}" = "workflow_run" ]; then
            case "${{ github.event.workflow_run.name }}" in
              "Verify on BscScan") KEY="VERIFY" ;;
              # Tambah mapping lain di bawah ini jika mau autopilot dari workflow lain:
              # "Solidity CI"|"Compile") KEY="VERIFY" ;;
              # "Deploy Website") KEY="WEBSITE" ;;
            esac
          else
            KEY="${{ inputs.task }}"
          fi
          echo "key=$KEY" >> "$GITHUB_OUTPUT"

      - name: Update README and Whitepaper
        if: steps.key.outputs.key != ''
        shell: bash
        run: |
          set -euo pipefail
          KEY="${{ steps.key.outputs.key }}"
          DATE="$(date +'%Y-%m-%d')"

          mark_done () {
            FILE="$1"
            MARK="<!-- ROADMAP:${KEY} -->"
            [ -f "$FILE" ] || return 0

            awk -v key="$MARK" -v date="$DATE" '
            function has_done(s){ return s ~ /\(done [0-9]{4}-[0-9]{2}-[0-9]{2}\)/ }
            {
              if ($0 ~ key) {
                # Hilangkan emoji ✅ agar gaya seragam
                gsub(/ ✅/,"")

                # Jika unchecked checkbox -> ubah ke [x] + tanggal
                if ($0 ~ /^\s*-\s*\[\s\]\s/) {
                  sub(/\[\s\]/,"[x]")
                  if (!has_done($0)) $0 = $0 " (done " date ")"
                }
                # Jika sudah [x] tapi belum ada tanggal -> tambahkan tanggal
                else if ($0 ~ /^\s*-\s*\[x\]\s/ && !has_done($0)) {
                  $0 = $0 " (done " date ")"
                }
                # Jika bukan format checklist (mis. pakai emoji) -> normalkan ke [x] + tanggal
                else if ($0 !~ /^\s*-\s*\[(\s|x)\]\s/) {
                  sub(/^\s*-\s*/,"- [x] ")
                  if (!has_done($0)) $0 = $0 " (done " date ")"
                }
              }
              print
            }' "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"
          }

          mark_done "README.md"
          mark_done "docs/Whitepaper.md"

          if git status --porcelain | grep -E "README\.md|docs/Whitepaper\.md" >/dev/null; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md docs/Whitepaper.md
            git commit -m "chore(roadmap): normalize & check ${KEY} on ${DATE}"
            git push
          else
            echo "No roadmap changes to commit."
          fi
