name: Roadmap Auto Check

on:
  # Otomatis saat workflow tertentu sukses
  workflow_run:
    workflows:
      - Verify on BscScan
      - Whitepaper release     # ← ceklis otomatis saat workflow ini sukses
    types: [completed]

  # Bisa juga manual dari tab Actions
  workflow_dispatch:
    inputs:
      task:
        description: "ROADMAP key to check"
        required: true
        default: "WHITEPAPER"   # ← default ke WHITEPAPER sesuai permintaan
        type: choice
        options:
          - VERIFY
          - WEBSITE
          - LIQ
          - WHITEPAPER
          - AIRDROP
          - LISTINGS
          - QUESTS
          - STAKING
          - AI
          - PARTNERS
          - BURN
          - CEX
          - COMMUNITY

permissions:
  contents: write

jobs:
  update-roadmap:
    # jalan jika manual, atau jika workflow target sukses
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Decide which ROADMAP key
        id: key
        shell: bash
        run: |
          KEY=""
          if [ "${{ github.event_name }}" = "workflow_run" ]; then
            case "${{ github.event.workflow_run.name }}" in
              "Verify on BscScan") KEY="VERIFY" ;;
              "Whitepaper release"|"Whitepaper") KEY="WHITEPAPER" ;;  # mapping fleksibel
            esac
          else
            KEY="${{ inputs.task }}"
          fi
          echo "key=$KEY" >> "$GITHUB_OUTPUT"

      - name: Update README and Whitepaper
        if: steps.key.outputs.key != ''
        shell: bash
        run: |
          set -euo pipefail
          KEY="${{ steps.key.outputs.key }}"
          DATE="$(date +'%Y-%m-%d')"

          mark_done () {
            FILE="$1"
            MARK="<!-- ROADMAP:${KEY} -->"
            [ -f "$FILE" ] || return 0

            awk -v key="$MARK" -v date="$DATE" '
            {
              if ($0 ~ key) {
                # jika masih unchecked: "- [ ] ..."
                if ($0 ~ /^\s*-\s*\[\s\]\s/) {
                  sub(/\[\s\]/, "[x]")
                  if ($0 !~ /\(done /) { $0 = $0 " (done " date ")" }
                }
                # jika sudah checked tapi belum ada tanggal
                else if ($0 ~ /^\s*-\s*\[x\]\s/ && $0 !~ /\(done /) {
                  $0 = $0 " (done " date ")"
                }
              }
              print
            }' "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"
          }

          mark_done "README.md"
          mark_done "docs/Whitepaper.md"

          if git status --porcelain | grep -E "README\.md|docs/Whitepaper\.md" >/dev/null; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md docs/Whitepaper.md
            git commit -m "chore(roadmap): auto-check $KEY on $DATE"
            git push
          else
            echo "No roadmap changes to commit."
          fi
