name: Solidity CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      
      - run: |
          node -v
          npm -v
          npm config get engine-strict --location=project

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci || npm ci --legacy-peer-deps
          else
            npm install --legacy-peer-deps
          fi

      - name: Compile contracts
        run: |
          npx hardhat clean
          npx hardhat compile

      # Kalau memang punya test, aktifkan step ini.
      # - name: Run tests
      #   run: npx hardhat test
