name: Solidity CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install solc
        run: npm install -g solc
      - name: Check solc version
        run: solc --version
      - name: Compile Contracts
        run: |
          echo "Compiling NickgenomPermit.sol..."
          solc --version
