name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "contracts/**"
      - "test/**"
      - "package.json"
      - "hardhat.*"
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci || npm ci --legacy-peer-deps
          else
            npm install --legacy-peer-deps
          fi

      - name: Clean & Compile
        run: |
          npx hardhat clean
          npx hardhat compile

      - name: Run tests
        run: npx hardhat test --reporter mocha

      - name: Upload coverage / logs (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-outputs-${{ github.run_id }}
          path: |
            coverage/
            junit.xml
          if-no-files-found: ignore
          retention-days: 1
