name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci || npm ci --legacy-peer-deps
          else
            npm install --legacy-peer-deps
          fi

      - name: Compile contracts
        run: |
          npx hardhat clean
          npx hardhat compile

      - name: Run tests (if any)
        shell: bash
        run: |
          set -e
          # Deteksi file test JS/TS (di test/ atau subfolder)
          if compgen -G "test/**/*.ts" > /dev/null || \
             compgen -G "test/**/*.js" > /dev/null || \
             compgen -G "test/*.ts" > /dev/null   || \
             compgen -G "test/*.js" > /dev/null; then
            echo "✅ Test files found. Running Hardhat tests…"
            npx hardhat test
          else
            echo "ℹ️  No test files found in ./test — skipping tests."
          fi
          
      # - name: Coverage (optional)
      #   run: npx hardhat coverage
      #
      # - name: Upload coverage report (optional)
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: coverage-${{ github.sha }}
      #     path: coverage/
      #     if-no-files-found: warn
      #     retention-days: 7
