name: Verify on BscScan

on:
  workflow_dispatch:
    inputs:
      network:
        description: "Network (bsc atau bscTestnet)"
        required: true
        default: "bsc"
        type: choice
        options: [bsc, bscTestnet]
        
env:
  CONTRACT_ADDRESS: "0x0353ad4cad5548de4230e36d86ed5536a0baca16"

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Show OZ version (debug)
        run: |
          node -p "require('@openzeppelin/contracts/package.json').version"
          npm ls @openzeppelin/contracts || true

      - name: Clean & Compile (force)
        run: |
          npx hardhat clean
          npx hardhat compile --force

      - name: Verify on BscScan
        env:
          BSCSCAN_API_KEY: ${{ secrets.BSCSCAN_API_KEY }}
        run: |
          if [ "${{ inputs.network }}" = "bsc" ]; then
            npx hardhat verify --network bsc "${CONTRACT_ADDRESS}"
          else
            npx hardhat verify --network bscTestnet "${CONTRACT_ADDRESS}"
          fi

      - name: Clean & Compile (force)
        run: |
          npx hardhat clean
          npx hardhat compile --force

      - name: Verify on BscScan
        env:
          BSCSCAN_API_KEY: ${{ secrets.BSCSCAN_API_KEY }}
        run: |
          if [ "${{ inputs.network }}" = "bsc" ]; then
            npx hardhat verify --network bsc "${CONTRACT_ADDRESS}"
          else
            npx hardhat verify --network bscTestnet "${CONTRACT_ADDRESS}"
          fi
