name: Verify on BscScan

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Show versions
        run: |
          node -v
          npm -v

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci || npm ci --legacy-peer-deps
          else
            npm install --legacy-peer-deps
          fi

      - name: Clean & Compile (force)
        run: |
          npx hardhat clean
          npx hardhat compile --force

      - name: Check required secrets
        run: |
          [ -n "${{ secrets.BSCSCAN_API_KEY }}" ] || { echo "Missing BSCSCAN_API_KEY"; exit 1; }
          [ -n "${{ secrets.CONTRACT_ADDRESS_BSC }}" ] || { echo "Missing CONTRACT_ADDRESS_BSC"; exit 1; }

      - name: Verify on BscScan (BSC mainnet)
        env:
          BSCSCAN_API_KEY: ${{ secrets.BSCSCAN_API_KEY }}
          ADDR: ${{ secrets.CONTRACT_ADDRESS_BSC }}
        run: |
          echo "Verifying address: $ADDR"
          npx hardhat verify --network bsc "$ADDR" \
            --contract "contracts/token/NickgenomPermit.sol:NickgenomPermit"

      - name: Upload build-info
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: hardhat-build-info-${{ github.sha }}
          path: artifacts/build-info/
          if-no-files-found: ignore
          retention-days: 1
          compression-level: 6
