name: Verify on BscScan

on:
  workflow_dispatch:
    inputs:
      network:
        description: "Network (bsc atau bscTestnet)"
        required: true
        default: "bsc"
        type: choice
        options: [bsc, bscTestnet]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0 # UPDATED TO SUPPORTED VERSION
          
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
          
      - name: Show OZ version (debug)
        run: node -p "require('@openzeppelin/contracts/package.json').version"
        
      - name: Clean & Compile (force)
        run: |
          npx hardhat clean
          npx hardhat compile --force
          
      - name: Verify on BscScan
        env:
          BSCSCAN_API_KEY: ${{ secrets.BSCSCAN_API_KEY }}
        run: |
          if [ "${{ inputs.network }}" = "bsc" ]; then
            echo "Verifying on BSC Mainnet..."
            npx hardhat verify --network bsc "${{ secrets.CONTRACT_ADDRESS_BSC }}" \
              --contract "contracts/token/NickgenomPermit.sol:NickgenomPermit" \
              --compiler-version 0.8.20 # SPECIFY ORIGINAL COMPILER VERSION
          else
            echo "Verifying on BSC Testnet..."
            npx hardhat verify --network bscTestnet "${{ secrets.CONTRACT_ADDRESS_BSCTESTNET }}" \
              --contract "contracts/token/NickgenPermit.sol:NickgenomPermit" \
              --compiler-version 0.8.20 # SPECIFY ORIGINAL COMPILER VERSION
          fi