name: Verify on BscScan

on:
  workflow_dispatch:
    inputs:
      network:
        description: "Network (bsc atau bscTestnet)"
        required: true
        default: "bsc"
        type: choice
        options: [bsc, bscTestnet]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.11.0
          
      - name: Install specific Hardhat version
        run: |
          npm install hardhat@2.22.5
          npm install
          
      - name: Show versions
        run: |
          echo "Node version: $(node --version)"
          echo "Hardhat version: $(npx hardhat --version)"
          echo "Network: ${{ inputs.network }}"
          echo "Contract Address: ${{ secrets.CONTRACT_ADDRESS_BSC }}"
          
      - name: Clean & Compile
        run: |
          npx hardhat clean
          npx hardhat compile
          
      - name: Verify on BscScan
        env:
          BSCSCAN_API_KEY: ${{ secrets.BSCSCAN_API_KEY }}
        run: |
          if [ "${{ inputs.network }}" = "bsc" ]; then
            echo "Verifying on BSC Mainnet..."
            npx hardhat verify --network bsc "${{ secrets.CONTRACT_ADDRESS_BSC }}" \
              --contract "contracts/token/NickgenomPermit.sol:NickgenomPermit" \
              --compiler 0.8.20 \
              --force
          else
            echo "Verifying on BSC Testnet..."
            npx hardhat verify --network bscTestnet "${{ secrets.CONTRACT_ADDRESS_BSCTESTNET }}" \
              --contract "contracts/token/NickgenomPermit.sol:NickgenomPermit" \
              --compiler 0.8.20 \
              --force
          fi